<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

class MakeSisFeatureCommand extends Command
{
    protected $signature = 'sis:make-feature {context : Bounded context e.g. Teacher} {--command= : Primary write use case name e.g. RegisterTeacher} {--query= : Primary read use case name e.g. GetTeacherProfile}';

    protected $description = 'Scaffold a bounded context feature skeleton (Domain + Application + Infrastructure + Tests)';

    public function handle(): int
    {
        $context = Str::studly($this->argument('context'));
        $root = base_path();

        $directories = [
            "app/Domain/{$context}/Entities",
            "app/Domain/{$context}/ValueObjects",
            "app/Domain/{$context}/Specifications",
            "app/Domain/{$context}/Events",
            "app/Domain/{$context}/Repositories",
            "app/Application/{$context}/Commands",
            "app/Application/{$context}/Queries",
            "app/Application/{$context}/DTOs",
            "app/Application/{$context}/Results",
            "app/Application/{$context}/Contracts",
            "app/Infrastructure/Persistence/{$context}",
            "tests/Unit/{$context}",
            "tests/Feature/{$context}",
        ];

        foreach ($directories as $dir) {
            $full = "{$root}/{$dir}";
            if (! is_dir($full)) {
                mkdir($full, 0755, true);
                file_put_contents("{$full}/.gitkeep", '');
            }
            $this->info("Ensured {$dir}");
        }

        $featureDoc = base_path(".cursor/architecture/features/{$context}.md");
        if (! file_exists($featureDoc)) {
            if (! is_dir(dirname($featureDoc))) {
                mkdir(dirname($featureDoc), 0755, true);
            }
            file_put_contents($featureDoc, $this->featureDocStub($context));
            $this->info("Created {$featureDoc}");
        }

        if ($command = $this->option('command')) {
            $this->call('sis:make-command', ['context' => $context, 'name' => $command]);
        }

        if ($query = $this->option('query')) {
            $this->call('sis:make-query', ['context' => $context, 'name' => $query]);
        }

        $this->newLine();
        $this->line('Next steps:');
        $this->line('  1. Define Domain Entity + Value Objects');
        $this->line('  2. Add repository port + Eloquent adapter');
        $this->line('  3. Implement Command/Query handlers');
        $this->line('  4. Wire bindings in ArchitectureServiceProvider');
        $this->line('  5. Add Controller + Form Request + Policy');
        $this->line('  6. php artisan architecture:validate --fitness');
        $this->line('  7. Complete FEATURE-DONE checklist in .cursor/architecture/FEATURE-DONE.md');

        return self::SUCCESS;
    }

    private function featureDocStub(string $context): string
    {
        return <<<MD
# Feature: {$context}

> Generated by `php artisan sis:make-feature {$context}`. Complete before marking done.

## Definition of Done

See [.cursor/architecture/FEATURE-DONE.md](../FEATURE-DONE.md).

## Bounded Context

- **Context:** {$context}
- **Primary aggregate:** TBD
- **Scoped by:** school_id + academic_year_id (if academic)

## Planned Use Cases

| Type | Name | Status |
|------|------|--------|
| Command | TBD | ⏳ |
| Query | TBD | ⏳ |

MD;
    }
}
