<?php

namespace App\Application\Student\DTOs;

final readonly class StudentListItemDTO
{
    public function __construct(
        public int $id,
        public string $studentCode,
        public string $fullName,
        public string $firstName,
        public ?string $fatherName,
        public ?string $grandfatherName,
        public ?string $greatGrandfatherName,
        public string $lastName,
        public ?string $motherName,
        public ?string $maternalFatherName,
        public ?string $maternalGrandfatherName,
        public ?string $guardianTripleName,
        public ?string $governorate,
        public ?string $neighborhood,
        public ?string $locality,
        public ?string $houseNumber,
        public string $birthDate,
        public ?string $birthPlace,
        public ?string $registrationPlace,
        public int $gender,
        public ?string $nationality,
        public int $religion,
        public ?string $mawalidDate,
        public ?string $nationalId,
        public ?string $previousSchoolName,
        public ?int $transferDocumentNumber,
        public ?string $transferDocumentDate,
        public ?string $schoolStartDate,
        public ?string $admittedClassName,
        public ?string $notes,
        public ?string $mobile,
        public ?string $guardianMobile,
        public ?string $email,
        public ?string $schoolName,
        public ?string $departmentName,
        public ?string $specializationName,
        public ?string $stageName,
        public ?string $sectionName,
        public int $status,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'student_code' => $this->studentCode,
            'full_name' => $this->fullName,
            'first_name' => $this->firstName,
            'father_name' => $this->fatherName,
            'grandfather_name' => $this->grandfatherName,
            'great_grandfather_name' => $this->greatGrandfatherName,
            'last_name' => $this->lastName,
            'mother_name' => $this->motherName,
            'maternal_father_name' => $this->maternalFatherName,
            'maternal_grandfather_name' => $this->maternalGrandfatherName,
            'guardian_triple_name' => $this->guardianTripleName,
            'governorate' => $this->governorate,
            'neighborhood' => $this->neighborhood,
            'locality' => $this->locality,
            'house_number' => $this->houseNumber,
            'birth_date' => $this->birthDate,
            'birth_place' => $this->birthPlace,
            'registration_place' => $this->registrationPlace,
            'gender' => $this->gender,
            'nationality' => $this->nationality,
            'religion' => $this->religion,
            'mawalid_date' => $this->mawalidDate,
            'national_id' => $this->nationalId,
            'previous_school_name' => $this->previousSchoolName,
            'transfer_document_number' => $this->transferDocumentNumber,
            'transfer_document_date' => $this->transferDocumentDate,
            'school_start_date' => $this->schoolStartDate,
            'admitted_class_name' => $this->admittedClassName,
            'notes' => $this->notes,
            'mobile' => $this->mobile,
            'guardian_mobile' => $this->guardianMobile,
            'email' => $this->email,
            'school_name' => $this->schoolName,
            'department_name' => $this->departmentName,
            'specialization_name' => $this->specializationName,
            'stage_name' => $this->stageName,
            'section_name' => $this->sectionName,
            'status' => $this->status,
        ];
    }
}
