<?php

namespace App\Application\Enrollment\DTOs;

final readonly class EnrollmentDTO
{
    public function __construct(
        public int $id,
        public int $studentId,
        public int $schoolId,
        public int $academicYearId,
        public int $classId,
        public int $sectionId,
        public string $enrollmentNumber,
        public int $status,
        public string $effectiveFrom,
        public ?string $effectiveTo = null,
        public ?int $specializationId = null,
        public ?int $branchId = null,
        public ?int $departmentId = null,
        public ?int $enrolledBy = null,
        public ?string $studentCode = null,
        public ?string $studentFullName = null,
        public ?string $studentFirstName = null,
        public ?string $studentFatherName = null,
        public ?string $studentGrandfatherName = null,
        public ?string $studentGreatGrandfatherName = null,
        public ?string $studentLastName = null,
        public ?int $studentGender = null,
        public ?string $studentBirthDate = null,
        public ?int $studentStatus = null,
        public ?string $schoolName = null,
        public ?string $academicYearName = null,
        public ?string $academicYearCode = null,
        public ?string $classCode = null,
        public ?string $className = null,
        public ?string $sectionCode = null,
        public ?string $sectionName = null,
        public ?string $specializationCode = null,
        public ?string $specializationName = null,
        public ?string $branchCode = null,
        public ?string $branchName = null,
        public ?string $gradeLevelCode = null,
        public ?string $gradeLevelName = null,
        public ?string $departmentName = null,
        public ?string $stageName = null,
        public ?string $createdAt = null,
        public ?string $updatedAt = null,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'student_id' => $this->studentId,
            'school_id' => $this->schoolId,
            'academic_year_id' => $this->academicYearId,
            'class_id' => $this->classId,
            'section_id' => $this->sectionId,
            'enrollment_number' => $this->enrollmentNumber,
            'status' => $this->status,
            'effective_from' => $this->effectiveFrom,
            'effective_to' => $this->effectiveTo,
            'specialization_id' => $this->specializationId,
            'branch_id' => $this->branchId,
            'department_id' => $this->departmentId,
            'enrolled_by' => $this->enrolledBy,
            'student_code' => $this->studentCode,
            'student_full_name' => $this->studentFullName,
            'student_first_name' => $this->studentFirstName,
            'student_father_name' => $this->studentFatherName,
            'student_grandfather_name' => $this->studentGrandfatherName,
            'student_great_grandfather_name' => $this->studentGreatGrandfatherName,
            'student_last_name' => $this->studentLastName,
            'student_gender' => $this->studentGender,
            'student_birth_date' => $this->studentBirthDate,
            'student_status' => $this->studentStatus,
            'school_name' => $this->schoolName,
            'academic_year_name' => $this->academicYearName,
            'academic_year_code' => $this->academicYearCode,
            'class_code' => $this->classCode,
            'class_name' => $this->className,
            'section_code' => $this->sectionCode,
            'section_name' => $this->sectionName,
            'specialization_code' => $this->specializationCode,
            'specialization_name' => $this->specializationName,
            'branch_code' => $this->branchCode,
            'branch_name' => $this->branchName,
            'grade_level_code' => $this->gradeLevelCode,
            'grade_level_name' => $this->gradeLevelName,
            'department_name' => $this->departmentName,
            'stage_name' => $this->stageName,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
        ];
    }
}
