<?php

namespace Tests\Feature\Database\PostgreSql;

use App\Database\SchemaHelper;
use App\Models\User;
use Database\Seeders\SecurityPermissionSeeder;
use Illuminate\Support\Facades\DB;
use PHPUnit\Framework\Attributes\Test;
use Tests\Concerns\InteractsWithSecurity;
use Tests\Support\Database\PostgreSqlIntegrationTestCase;

/**
 * Add → مدرسة / مديرية: organization registry sheets on the admission page.
 * Codes are generated by the system; create links the creator with the roles they
 * hold in the current school; school edit is limited to linked schools.
 */
final class SchoolRegistryHttpPostgreSqlTest extends PostgreSqlIntegrationTestCase
{
    use InteractsWithSecurity;

    #[Test]
    public function creates_a_school_and_links_the_creator_with_the_same_roles(): void
    {
        $schoolId = $this->createSchool('SCH-REG', 'Registry School');
        $user = $this->actingAsSchoolManager($schoolId);
        $directorateId = $this->directorateOf($schoolId);

        $this->withHeader('X-Idempotency-Key', 'school-create-1')
            ->from('/admission')
            ->post('/organization/schools', [
                'name' => 'مدرسة الصناعة الثانية',
                'directorate_id' => $directorateId,
                'phone' => '07700000000',
                'email' => 'second@sis.local',
                'address' => 'بغداد',
            ])
            ->assertSessionHasNoErrors()
            ->assertRedirect('/admission');

        $new = DB::table(SchemaHelper::qualified('organization', 'schools'))
            ->where('name', 'مدرسة الصناعة الثانية')->first(['id', 'code']);
        $this->assertNotNull($new);
        $newId = (int) $new->id;
        $this->assertMatchesRegularExpression('/^SCH-[0-9]{4,}$/', (string) $new->code);
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), [
            'id' => $newId,
            'directorate_id' => $directorateId,
            'school_type' => 2,
            'status' => 1,
        ]);

        $rolesAtSource = $this->roleIds($user->id, $schoolId);
        $this->assertNotEmpty($rolesAtSource);
        $this->assertSame($rolesAtSource, $this->roleIds($user->id, $newId));
    }

    #[Test]
    public function replaying_the_same_idempotency_key_does_not_create_twice(): void
    {
        $schoolId = $this->createSchool('SCH-IDM', 'Idempotent School');
        $this->actingAsSchoolManager($schoolId);
        $payload = ['name' => 'مدرسة مكررة', 'directorate_id' => $this->directorateOf($schoolId)];

        $this->withHeader('X-Idempotency-Key', 'school-create-same')->post('/organization/schools', $payload)
            ->assertSessionHasNoErrors();
        $this->withHeader('X-Idempotency-Key', 'school-create-same')->post('/organization/schools', $payload)
            ->assertSessionHasNoErrors();

        $this->assertSame(1, DB::table(SchemaHelper::qualified('organization', 'schools'))
            ->where('name', 'مدرسة مكررة')->count());
    }

    #[Test]
    public function generates_unique_codes_and_rejects_client_codes(): void
    {
        $schoolId = $this->createSchool('SCH-GEN', 'Generated Codes School');
        $this->actingAsSchoolManager($schoolId);
        $directorateId = $this->directorateOf($schoolId);

        foreach (['أولى', 'ثانية'] as $index => $name) {
            $this->withHeader('X-Idempotency-Key', 'school-create-gen-'.$index)
                ->post('/organization/schools', ['name' => $name, 'directorate_id' => $directorateId])
                ->assertSessionHasNoErrors();
        }

        $codes = DB::table(SchemaHelper::qualified('organization', 'schools'))
            ->whereIn('name', ['أولى', 'ثانية'])->pluck('code')->all();
        $this->assertCount(2, array_unique($codes));

        $this->withHeader('X-Idempotency-Key', 'school-create-code')
            ->post('/organization/schools', [
                'code' => 'MY-CODE',
                'name' => 'برمز',
                'directorate_id' => $directorateId,
            ])
            ->assertSessionHasErrors(['code']);
    }

    #[Test]
    public function updates_a_linked_school_but_not_its_code(): void
    {
        $schoolId = $this->createSchool('SCH-UPD', 'Update School');
        $this->actingAsSchoolManager($schoolId);

        $this->withHeader('X-Idempotency-Key', 'school-update-1')
            ->patch("/organization/schools/{$schoolId}", [
                'name' => 'اسم معدّل',
                'phone' => '07711111111',
                'email' => null,
            ])
            ->assertSessionHasNoErrors();

        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), [
            'id' => $schoolId,
            'code' => 'SCH-UPD',
            'name' => 'اسم معدّل',
            'phone' => '07711111111',
            'email' => null,
        ]);

        $this->withHeader('X-Idempotency-Key', 'school-update-2')
            ->patch("/organization/schools/{$schoolId}", ['code' => 'HACKED'])
            ->assertSessionHasErrors(['code']);
    }

    #[Test]
    public function deactivates_and_reactivates_a_linked_school_only(): void
    {
        $schoolId = $this->createSchool('SCH-ST1', 'Status School One');
        $otherId = $this->createSchool('SCH-ST2', 'Status School Two');
        $this->actingAsSchoolManager($schoolId);

        $this->withHeader('X-Idempotency-Key', 'school-deactivate')
            ->post("/organization/schools/{$schoolId}/deactivate")
            ->assertSessionHasNoErrors();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), ['id' => $schoolId, 'status' => 2]);

        $this->withHeader('X-Idempotency-Key', 'school-reactivate')
            ->post("/organization/schools/{$schoolId}/reactivate")
            ->assertSessionHasNoErrors();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), ['id' => $schoolId, 'status' => 1]);

        $this->withHeader('X-Idempotency-Key', 'school-deactivate-foreign')
            ->post("/organization/schools/{$otherId}/deactivate")
            ->assertForbidden();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), ['id' => $otherId, 'status' => 1]);

        $this->withHeader('X-Idempotency-Key', 'school-status-field')
            ->patch("/organization/schools/{$schoolId}", ['status' => 2])
            ->assertSessionHasErrors(['status']);
    }

    #[Test]
    public function cannot_edit_a_school_the_user_is_not_linked_to(): void
    {
        $schoolId = $this->createSchool('SCH-OWN', 'Own School');
        $otherId = $this->createSchool('SCH-FOR', 'Foreign School');
        $this->actingAsSchoolManager($schoolId);

        $this->withHeader('X-Idempotency-Key', 'school-update-foreign')
            ->patch("/organization/schools/{$otherId}", ['name' => 'استيلاء'])
            ->assertForbidden();

        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), [
            'id' => $otherId,
            'name' => 'Foreign School',
        ]);
    }

    #[Test]
    public function users_without_the_school_permission_cannot_create(): void
    {
        $schoolId = $this->createSchool('SCH-NOP', 'No Permission School');
        $this->actingAsAdmissionOnly($schoolId);

        $this->withHeader('X-Idempotency-Key', 'school-create-denied')
            ->post('/organization/schools', [
                'name' => 'مرفوضة',
                'directorate_id' => $this->directorateOf($schoolId),
            ])
            ->assertForbidden();

        $this->assertDatabaseMissing(SchemaHelper::qualified('organization', 'schools'), ['name' => 'مرفوضة']);
    }

    #[Test]
    public function adds_and_edits_a_directorate_and_uses_it_for_a_school(): void
    {
        $schoolId = $this->createSchool('SCH-DIR', 'Directorate School');
        $this->actingAsSchoolManager($schoolId);

        $this->withHeader('X-Idempotency-Key', 'directorate-create-1')
            ->post('/organization/directorates', ['name' => 'مديرية تربية الكرخ', 'region' => 'بغداد'])
            ->assertSessionHasNoErrors();

        $directorate = DB::table(SchemaHelper::qualified('organization', 'directorates'))
            ->where('name', 'مديرية تربية الكرخ')->first(['id', 'code', 'ministry_id', 'status']);
        $this->assertNotNull($directorate);
        $this->assertMatchesRegularExpression('/^DIR-[0-9]{4,}$/', (string) $directorate->code);
        $this->assertSame(1, (int) $directorate->status);
        $this->assertGreaterThan(0, (int) $directorate->ministry_id);

        $this->withHeader('X-Idempotency-Key', 'directorate-update-1')
            ->patch("/organization/directorates/{$directorate->id}", ['name' => 'مديرية الكرخ الأولى', 'region' => null])
            ->assertSessionHasNoErrors();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'directorates'), [
            'id' => $directorate->id,
            'name' => 'مديرية الكرخ الأولى',
            'region' => null,
        ]);

        $this->withHeader('X-Idempotency-Key', 'school-in-new-directorate')
            ->post('/organization/schools', ['name' => 'مدرسة في الكرخ', 'directorate_id' => $directorate->id])
            ->assertSessionHasNoErrors();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'schools'), [
            'name' => 'مدرسة في الكرخ',
            'directorate_id' => $directorate->id,
        ]);
    }

    #[Test]
    public function directorates_require_the_directorate_permission(): void
    {
        $schoolId = $this->createSchool('SCH-DNP', 'No Directorate Permission');
        $this->actingAsAdmissionOnly($schoolId);

        $this->withHeader('X-Idempotency-Key', 'directorate-denied')
            ->post('/organization/directorates', ['name' => 'مرفوضة'])
            ->assertForbidden();
    }

    #[Test]
    public function places_the_users_schools_in_a_new_or_edited_directorate(): void
    {
        $schoolId = $this->createSchool('SCH-PLC', 'Placed School');
        $this->actingAsSchoolManager($schoolId);
        $originalDirectorate = $this->directorateOf($schoolId);

        $this->withHeader('X-Idempotency-Key', 'directorate-with-school')
            ->post('/organization/directorates', ['name' => 'مديرية جديدة', 'school_ids' => [$schoolId]])
            ->assertSessionHasNoErrors();
        $newDirectorate = (int) DB::table(SchemaHelper::qualified('organization', 'directorates'))
            ->where('name', 'مديرية جديدة')->value('id');
        $this->assertSame($newDirectorate, $this->directorateOf($schoolId));

        // Moving back is done by ticking the school in the other directorate.
        $this->withHeader('X-Idempotency-Key', 'directorate-move-back')
            ->patch("/organization/directorates/{$originalDirectorate}", ['school_ids' => [$schoolId]])
            ->assertSessionHasNoErrors();
        $this->assertSame($originalDirectorate, $this->directorateOf($schoolId));

        // Unticking a school without giving it another directorate is refused.
        $this->withHeader('X-Idempotency-Key', 'directorate-remove')
            ->patch("/organization/directorates/{$originalDirectorate}", ['school_ids' => []])
            ->assertSessionHasErrors(['directorate' => 'organization.directorate_school_removal']);
        $this->assertSame($originalDirectorate, $this->directorateOf($schoolId));
    }

    #[Test]
    public function cannot_place_a_school_the_user_is_not_linked_to(): void
    {
        $schoolId = $this->createSchool('SCH-PL1', 'Mine');
        $otherId = $this->createSchool('SCH-PL2', 'Not Mine');
        $this->actingAsSchoolManager($schoolId);
        $before = $this->directorateOf($otherId);

        $this->withHeader('X-Idempotency-Key', 'directorate-foreign-school')
            ->post('/organization/directorates', ['name' => 'استيلاء', 'school_ids' => [$otherId]])
            ->assertSessionHasErrors(['directorate' => 'organization.school_not_linked']);

        $this->assertSame($before, $this->directorateOf($otherId));
        $this->assertDatabaseMissing(SchemaHelper::qualified('organization', 'directorates'), ['name' => 'استيلاء']);
    }

    #[Test]
    public function deactivates_only_directorates_without_active_schools(): void
    {
        $schoolId = $this->createSchool('SCH-STS', 'Status School');
        $this->actingAsSchoolManager($schoolId);
        $busy = $this->directorateOf($schoolId);

        $this->withHeader('X-Idempotency-Key', 'directorate-deactivate-busy')
            ->post("/organization/directorates/{$busy}/deactivate")
            ->assertSessionHasErrors(['directorate' => 'organization.directorate_has_schools']);

        $this->withHeader('X-Idempotency-Key', 'directorate-empty')
            ->post('/organization/directorates', ['name' => 'مديرية فارغة'])
            ->assertSessionHasNoErrors();
        $empty = (int) DB::table(SchemaHelper::qualified('organization', 'directorates'))
            ->where('name', 'مديرية فارغة')->value('id');

        $this->withHeader('X-Idempotency-Key', 'directorate-deactivate-empty')
            ->post("/organization/directorates/{$empty}/deactivate")
            ->assertSessionHasNoErrors();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'directorates'), ['id' => $empty, 'status' => 2]);

        // Inactive directorates are not offered to schools and take no new schools.
        $this->withHeader('X-Idempotency-Key', 'directorate-inactive-place')
            ->patch("/organization/directorates/{$empty}", ['school_ids' => [$schoolId]])
            ->assertSessionHasErrors(['directorate' => 'organization.directorate_inactive']);

        $this->withHeader('X-Idempotency-Key', 'directorate-reactivate')
            ->post("/organization/directorates/{$empty}/reactivate")
            ->assertSessionHasNoErrors();
        $this->assertDatabaseHas(SchemaHelper::qualified('organization', 'directorates'), ['id' => $empty, 'status' => 1]);

        $this->withHeader('X-Idempotency-Key', 'directorate-status-field')
            ->patch("/organization/directorates/{$empty}", ['status' => 2])
            ->assertSessionHasErrors(['status']);
    }

    private function actingAsSchoolManager(int $schoolId): User
    {
        $user = User::factory()->create();
        $seeder = app(SecurityPermissionSeeder::class);
        $seeder->grantStudentManager($user, $schoolId);
        $seeder->assignRole($user, 'admission_manager', $schoolId);
        $seeder->grantSchoolManager($user, $schoolId);
        $this->actingAs($user);
        $this->withSession(['current_school_id' => $schoolId]);

        return $user;
    }

    private function actingAsAdmissionOnly(int $schoolId): void
    {
        $user = User::factory()->create();
        $seeder = app(SecurityPermissionSeeder::class);
        $seeder->run();
        $seeder->assignRole($user, 'admission_manager', $schoolId);
        $this->actingAs($user);
        $this->withSession(['current_school_id' => $schoolId]);
    }

    private function directorateOf(int $schoolId): int
    {
        return (int) DB::table(SchemaHelper::qualified('organization', 'schools'))
            ->where('id', $schoolId)->value('directorate_id');
    }

    /** @return list<int> */
    private function roleIds(int $userId, int $schoolId): array
    {
        return DB::table(SchemaHelper::qualified('security', 'user_roles'))
            ->where('user_id', $userId)
            ->where('school_id', $schoolId)
            ->orderBy('role_id')
            ->pluck('role_id')
            ->map(static fn ($id): int => (int) $id)
            ->all();
    }
}
