<?php

use App\Database\SchemaHelper;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Timetable workbench — display attributes live with the entity that owns them (never copied into timetable):
 *
 * - `abbreviation` (VARCHAR 20, nullable) + `color_hue` (SMALLINT 0–359, nullable = the timetable's default wheel)
 *   on curriculum.subjects, teachers.teachers, organization.branches / departments / rooms, enrollment.classes / sections.
 *   The colour is a hue on the approved card palette (lightness / saturation stay governed by the stylesheet).
 * - teachers.academic_titles   reference data «اللقب العلمي» (global, seeded); teachers.teachers.academic_title_id.
 * - organization.room_types    managed room types; school_id NULL = system default types shared by every school.
 * - organization.rooms         room number, building, floor, location, owning department, managed type, practical
 *                              support, equipment, suitable activities, notes. The legacy `room_type` (1 classroom,
 *                              2 practical — matched by the solver) is kept and follows `supports_practical`.
 *
 * Additive only: no column dropped, no data removed; down() removes exactly what up() added.
 */
return new class extends Migration
{
    /** @var list<string> */
    private const DISPLAY_TABLES = [
        'curriculum.subjects',
        'teachers.teachers',
        'organization.branches',
        'organization.departments',
        'organization.rooms',
        'enrollment.classes',
        'enrollment.sections',
    ];

    public function up(): void
    {
        if (! SchemaHelper::isPostgreSql()) {
            return;
        }

        foreach (self::DISPLAY_TABLES as $table) {
            $name = str_replace('.', '_', $table);
            DB::statement("ALTER TABLE {$table} ADD COLUMN IF NOT EXISTS abbreviation VARCHAR(20)");
            DB::statement("ALTER TABLE {$table} ADD COLUMN IF NOT EXISTS color_hue SMALLINT");
            DB::statement("ALTER TABLE {$table} ADD CONSTRAINT {$name}_color_hue_check CHECK (color_hue IS NULL OR color_hue BETWEEN 0 AND 359)");
            DB::statement("ALTER TABLE {$table} ADD CONSTRAINT {$name}_abbreviation_check CHECK (abbreviation IS NULL OR length(btrim(abbreviation)) > 0)");
        }

        // «اللقب العلمي» — global reference data (same posture as curriculum.subjects: no school_id, no hard delete).
        DB::statement('
            CREATE TABLE teachers.academic_titles (
                id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR(20) NOT NULL UNIQUE,
                name VARCHAR(60) NOT NULL,
                abbreviation VARCHAR(20),
                sort_order SMALLINT NOT NULL DEFAULT 0,
                status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        ');
        $titles = [
            ['TEACHER', 'مدرس', 'م.', 10],
            ['SENIOR_TEACHER', 'مدرس أول', 'م.أ', 20],
            ['ASSISTANT_TEACHER', 'مدرس مساعد', 'م.م', 30],
            ['PROFESSOR', 'أستاذ', 'أ.', 40],
            ['ASSISTANT_PROFESSOR', 'أستاذ مساعد', 'أ.م', 50],
            ['DOCTOR', 'دكتور', 'د.', 60],
            ['ENGINEER', 'مهندس', 'مهـ.', 70],
            ['INSTRUCTOR', 'معلم', 'مع.', 80],
            ['TECHNICAL_TRAINER', 'مدرب فني', 'م.ف', 90],
        ];
        foreach ($titles as [$code, $name, $abbreviation, $order]) {
            DB::insert('INSERT INTO teachers.academic_titles (code, name, abbreviation, sort_order) VALUES (?, ?, ?, ?)', [$code, $name, $abbreviation, $order]);
        }
        DB::statement("
            CREATE OR REPLACE FUNCTION teachers.reject_academic_titles_delete()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'Hard delete of teachers.academic_titles is forbidden — deactivate via status'
                    USING ERRCODE = 'check_violation';
            END; $$
        ");
        DB::statement('CREATE TRIGGER academic_titles_reject_delete BEFORE DELETE ON teachers.academic_titles FOR EACH ROW EXECUTE FUNCTION teachers.reject_academic_titles_delete()');
        DB::statement('ALTER TABLE teachers.teachers ADD COLUMN academic_title_id SMALLINT REFERENCES teachers.academic_titles(id) ON DELETE RESTRICT');

        // Managed room types: system defaults (school_id NULL) + the school's own.
        DB::statement('
            CREATE TABLE organization.room_types (
                id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                school_id BIGINT REFERENCES organization.schools(id) ON DELETE RESTRICT,
                code VARCHAR(30) NOT NULL,
                name VARCHAR(100) NOT NULL,
                abbreviation VARCHAR(20),
                kind SMALLINT NOT NULL CHECK (kind IN (1, 2, 3, 4, 9)),
                supports_practical BOOLEAN NOT NULL DEFAULT FALSE,
                color_hue SMALLINT CHECK (color_hue IS NULL OR color_hue BETWEEN 0 AND 359),
                sort_order SMALLINT NOT NULL DEFAULT 0,
                status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        ');
        DB::statement('CREATE UNIQUE INDEX room_types_code_uidx ON organization.room_types (COALESCE(school_id, 0), code)');
        $types = [
            // code, name, abbreviation, kind (1 صف · 2 مختبر · 3 ورشة · 4 قاعة · 9 أخرى), practical, hue
            ['CLASSROOM', 'صف دراسي', 'صف', 1, false, 205, 10],
            ['LAB', 'مختبر', 'مختبر', 2, true, 160, 20],
            ['COMPUTER_LAB', 'مختبر حاسوب', 'م.حاسوب', 2, true, 190, 30],
            ['ELECTRICAL_LAB', 'مختبر كهرباء', 'م.كهرباء', 2, true, 45, 40],
            ['CHEMISTRY_LAB', 'مختبر كيمياء', 'م.كيمياء', 2, true, 120, 50],
            ['WORKSHOP', 'ورشة', 'ورشة', 3, true, 25, 60],
            ['INDUSTRIAL_WORKSHOP', 'ورشة صناعية', 'و.صناعية', 3, true, 10, 70],
            ['HALL', 'قاعة', 'قاعة', 4, false, 260, 80],
            ['OTHER', 'غرفة أخرى', 'أخرى', 9, false, 300, 90],
        ];
        foreach ($types as [$code, $name, $abbreviation, $kind, $practical, $hue, $order]) {
            DB::insert(
                'INSERT INTO organization.room_types (school_id, code, name, abbreviation, kind, supports_practical, color_hue, sort_order) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?)',
                [$code, $name, $abbreviation, $kind, $practical, $hue, $order],
            );
        }
        DB::statement("
            CREATE OR REPLACE FUNCTION organization.reject_room_types_delete()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'Hard delete of organization.room_types is forbidden — deactivate via status'
                    USING ERRCODE = 'check_violation';
            END; $$
        ");
        DB::statement('CREATE TRIGGER room_types_reject_delete BEFORE DELETE ON organization.room_types FOR EACH ROW EXECUTE FUNCTION organization.reject_room_types_delete()');

        DB::statement('
            ALTER TABLE organization.rooms
                ADD COLUMN room_number VARCHAR(20),
                ADD COLUMN building VARCHAR(100),
                ADD COLUMN floor SMALLINT CHECK (floor IS NULL OR floor BETWEEN -5 AND 100),
                ADD COLUMN location VARCHAR(150),
                ADD COLUMN department_id BIGINT REFERENCES organization.departments(id) ON DELETE RESTRICT,
                ADD COLUMN room_type_id BIGINT REFERENCES organization.room_types(id) ON DELETE RESTRICT,
                ADD COLUMN supports_practical BOOLEAN NOT NULL DEFAULT FALSE,
                ADD COLUMN equipment TEXT,
                ADD COLUMN suitable_for TEXT,
                ADD COLUMN notes TEXT
        ');
        // Existing rooms: classroom → «صف دراسي», practical → «مختبر» (supports practical).
        DB::statement("
            UPDATE organization.rooms r
            SET room_type_id = t.id, supports_practical = (r.room_type = 2)
            FROM organization.room_types t
            WHERE t.school_id IS NULL AND t.code = CASE WHEN r.room_type = 2 THEN 'LAB' ELSE 'CLASSROOM' END
        ");
        DB::statement('CREATE INDEX rooms_room_type_idx ON organization.rooms (room_type_id)');
    }

    public function down(): void
    {
        if (! SchemaHelper::isPostgreSql()) {
            return;
        }

        DB::statement('DROP INDEX IF EXISTS organization.rooms_room_type_idx');
        DB::statement('
            ALTER TABLE organization.rooms
                DROP COLUMN IF EXISTS room_number,
                DROP COLUMN IF EXISTS building,
                DROP COLUMN IF EXISTS floor,
                DROP COLUMN IF EXISTS location,
                DROP COLUMN IF EXISTS department_id,
                DROP COLUMN IF EXISTS room_type_id,
                DROP COLUMN IF EXISTS supports_practical,
                DROP COLUMN IF EXISTS equipment,
                DROP COLUMN IF EXISTS suitable_for,
                DROP COLUMN IF EXISTS notes
        ');
        DB::statement('DROP TRIGGER IF EXISTS room_types_reject_delete ON organization.room_types');
        DB::statement('DROP TABLE IF EXISTS organization.room_types');
        DB::statement('DROP FUNCTION IF EXISTS organization.reject_room_types_delete()');

        DB::statement('ALTER TABLE teachers.teachers DROP COLUMN IF EXISTS academic_title_id');
        DB::statement('DROP TRIGGER IF EXISTS academic_titles_reject_delete ON teachers.academic_titles');
        DB::statement('DROP TABLE IF EXISTS teachers.academic_titles');
        DB::statement('DROP FUNCTION IF EXISTS teachers.reject_academic_titles_delete()');

        foreach (self::DISPLAY_TABLES as $table) {
            $name = str_replace('.', '_', $table);
            DB::statement("ALTER TABLE {$table} DROP CONSTRAINT IF EXISTS {$name}_color_hue_check");
            DB::statement("ALTER TABLE {$table} DROP CONSTRAINT IF EXISTS {$name}_abbreviation_check");
            DB::statement("ALTER TABLE {$table} DROP COLUMN IF EXISTS abbreviation");
            DB::statement("ALTER TABLE {$table} DROP COLUMN IF EXISTS color_hue");
        }
    }
};
