<?php

return [
    'permissions' => [
        'students.view' => 'View student records',
        'students.create' => 'Create student records',
        'students.update' => 'Update student records',
        'students.view_pii' => 'View student PII (national ID)',
        'enrollment.view' => 'View enrollment records',
        'enrollment.create' => 'Create enrollment records',
        'enrollment.update' => 'Update enrollment placement',
        'enrollment.cancel' => 'Cancel enrollment records',
        'grades.view' => 'View student grades',
        'grades.create' => 'Enter student grades',
        'grades.correct' => 'Correct student grades',
        'grades.void' => 'Void student grades',
        'grades.finalize' => 'Finalize student grades',
        'exam.create' => 'Create exams',
        'exam.update' => 'Update exams',
        'exam.cancel' => 'Cancel exams',
        'exam.session.create' => 'Create exam sessions',
        'exam.session.update' => 'Update exam sessions (includes CancelExamSession)',
        'exam.session.open' => 'Open exam sessions',
        'exam.session.close' => 'Close exam sessions',
        'exam.enrollment.create' => 'Create exam enrollments',
        'exam.enrollment.update' => 'Update exam enrollments',
        'exam.enrollment.cancel' => 'Cancel exam enrollments',
        'exam.enrollment.present' => 'Mark exam enrollment present',
        'attendance.view' => 'View attendance sessions and records',
        'attendance.session.create' => 'Create attendance sessions',
        'attendance.mark' => 'Mark attendance for open sessions',
        'attendance.correct' => 'Correct attendance with audited reason',
        'attendance.session.close' => 'Close open attendance sessions',
        'attendance.session.cancel' => 'Cancel open or closed attendance sessions',
        'timetable.schedule.create' => 'Create timetable schedules',
        'timetable.view' => 'View timetable schedules',
        'timetable.schedule.update' => 'Update active timetable schedules',
        'timetable.schedule.cancel' => 'Cancel active timetable schedules',
        'timetable.exception.create' => 'Create timetable schedule exceptions',
        'timetable.exception.update' => 'Update timetable schedule exceptions',
        'results.view' => 'View official results, GPA, ranking, and issued transcript metadata',
        'results.calculate' => 'Calculate operational term/annual/GPA results',
        'results.finalize' => 'Finalize official term/annual/GPA results',
        'results.ranking.build' => 'Build comparative ranking snapshots',
        'results.transcript.issue' => 'Issue transcript metadata (no PDF bytes)',
        'results.rebuild' => 'Rebuild operational or official term/annual/GPA results',
        'portal.results.view' => 'View own or linked-student official results via portal (ownership required)',
        'portal.scopes.manage' => 'Link/unlink/list portal party scopes (student|guardian) for users',
        'teachers.view' => 'View teachers assigned to the current school',
        'teachers.manage' => 'Register and manage teachers for the current school',
        'promotion.view' => 'View promotion rules and decisions for the current school',
        'promotion.manage' => 'Manage promotion rules and record promotion decisions',
        'transfers.view' => 'View transfer requests involving the current school',
        'transfers.manage' => 'Create and decide transfer requests involving the current school',
        'documents.view' => 'View document metadata for the current school',
        'documents.manage' => 'Register document metadata for the current school',
        'finance.view' => 'View finance fee catalog for the current school',
        'finance.manage' => 'Manage finance fee catalog for the current school (no payments in v1)',
        'communication.view' => 'View notification templates for the current school',
        'communication.manage' => 'Manage notification templates for the current school (no send in v1)',
        'workflow.view' => 'View approval flow definitions for the current school',
        'workflow.manage' => 'Manage approval flow definitions and cancel open approval requests',
        'workflow.decide' => 'Decide pending approval requests when assigned the step role',
        'hr.view' => 'View HR job positions and employees for the current school',
        'hr.manage' => 'Manage HR job positions and register employees for the current school (no payroll)',
        'vocational.manage' => 'Manage vocational specializations, tracks, and subject links',
        'vocational.view' => 'View vocational specializations, tracks, and subject links',
        'curriculum.view' => 'View curriculum subject prerequisites',
        'curriculum.manage' => 'Manage curriculum subject prerequisites (soft deactivate only)',
        'audit.view' => 'View domain audit logs for the current school',
        'audit.manage' => 'Register domain audit log entries for the current school',
        'security.manage_users' => 'Manage users and security settings',
    ],

    'roles' => [
        'student_manager' => [
            'students.view',
            'students.create',
            'students.update',
            'students.view_pii',
        ],
        'student_viewer' => [
            'students.view',
        ],
        'enrollment_manager' => [
            'enrollment.view',
            'enrollment.create',
            'enrollment.update',
            'enrollment.cancel',
            'students.view',
        ],
        'enrollment_viewer' => [
            'enrollment.view',
            'students.view',
        ],
        'grades_manager' => [
            'grades.view',
            'grades.create',
            'grades.correct',
            'grades.void',
            'grades.finalize',
            'exam.create',
            'exam.update',
            'exam.cancel',
            'exam.session.create',
            'exam.session.update',
            'exam.session.open',
            'exam.session.close',
            'exam.enrollment.create',
            'exam.enrollment.update',
            'exam.enrollment.cancel',
            'exam.enrollment.present',
            'students.view',
            'enrollment.view',
        ],
        'grades_teacher' => [
            'grades.view',
            'grades.create',
            'students.view',
            'enrollment.view',
        ],
        'grades_viewer' => [
            'grades.view',
            'students.view',
            'enrollment.view',
        ],
        'attendance_viewer' => [
            'attendance.view',
        ],
        'attendance_teacher' => [
            'attendance.view',
            'attendance.session.create',
            'attendance.mark',
            'attendance.session.close',
        ],
        'attendance_manager' => [
            'attendance.view',
            'attendance.session.create',
            'attendance.mark',
            'attendance.correct',
            'attendance.session.close',
            'attendance.session.cancel',
        ],
        'timetable_manager' => [
            'timetable.view',
            'timetable.schedule.create',
            'timetable.schedule.update',
            'timetable.schedule.cancel',
            'timetable.exception.create',
            'timetable.exception.update',
        ],
        'results_viewer' => [
            'results.view',
        ],
        'results_manager' => [
            'results.view',
            'results.calculate',
            'results.finalize',
            'results.ranking.build',
            'results.transcript.issue',
            'results.rebuild',
        ],
        'portal_results_viewer' => [
            'portal.results.view',
        ],
        'portal_scopes_manager' => [
            'portal.scopes.manage',
        ],
        'teachers_viewer' => [
            'teachers.view',
        ],
        'teachers_manager' => [
            'teachers.view',
            'teachers.manage',
        ],
        'promotion_viewer' => [
            'promotion.view',
        ],
        'promotion_manager' => [
            'promotion.view',
            'promotion.manage',
        ],
        'transfers_viewer' => [
            'transfers.view',
        ],
        'transfers_manager' => [
            'transfers.view',
            'transfers.manage',
            'workflow.decide',
        ],
        'documents_viewer' => [
            'documents.view',
        ],
        'documents_manager' => [
            'documents.view',
            'documents.manage',
        ],
        'finance_viewer' => [
            'finance.view',
        ],
        'finance_manager' => [
            'finance.view',
            'finance.manage',
        ],
        'communication_viewer' => [
            'communication.view',
        ],
        'communication_manager' => [
            'communication.view',
            'communication.manage',
        ],
        'audit_viewer' => [
            'audit.view',
        ],
        'audit_manager' => [
            'audit.view',
            'audit.manage',
        ],
        'workflow_viewer' => [
            'workflow.view',
        ],
        'workflow_manager' => [
            'workflow.view',
            'workflow.manage',
            'workflow.decide',
        ],
        'hr_viewer' => [
            'hr.view',
        ],
        'hr_manager' => [
            'hr.view',
            'hr.manage',
        ],
        'vocational_manager' => [
            'vocational.view',
            'vocational.manage',
        ],
        'curriculum_viewer' => [
            'curriculum.view',
        ],
        'curriculum_manager' => [
            'curriculum.view',
            'curriculum.manage',
        ],
    ],

    'rate_limits' => [
        'api' => ['max_attempts' => 120, 'decay_minutes' => 1],
        'api_students' => ['max_attempts' => 60, 'decay_minutes' => 1],
        'api_search' => ['max_attempts' => 30, 'decay_minutes' => 1],
    ],

    'headers' => [
        'X-Content-Type-Options' => 'nosniff',
        'X-Frame-Options' => 'SAMEORIGIN',
        'Referrer-Policy' => 'strict-origin-when-cross-origin',
        'Permissions-Policy' => 'camera=(), microphone=(), geolocation=()',
    ],

    'public_api_routes' => [
        'api.health',
    ],

    'dependency_audit_enabled' => env('SECURITY_DEPENDENCY_AUDIT_ENABLED', true),

    'allow_implicit_single_school' => false,
];
